language: node_js
node_js: 16
addons:
apt:
sources:
- travis-ci/sqlite3
packages:
- sqlite3
sudo: false
before_script:
- npm install -g mocha
script:
- npm test
deploy:
provider: heroku
skip_cleanup: true
api_key: 48b3ee8e-a99b-4f6a-a6c2-d3be64fa0866
secure: $HEROKU_API_KEY
app: ford-api-luisantoniobusma
edge: true
