language: node_js
node_js: 16
addons:
apt:
sources:
- travis-ci/sqlite3
packages:
- sqlite3
sudo: false
before_script:
- npm install -g mocha
script:
- npm test
deploy:
provider: heroku
skip_cleanup: true
api_key:
secure: $HEROKU_API_KEY
app: ford-api-luisantoniobusma
edge: true